### ISSUE TITLE
Consideration for Production Use

### ISSUE THREAD

**Issue by aaademosu** [devcenter-square/states-cities#7]
I am considering the use of this API in production to replace various applications. Seen some changes that are breaking changes and would like to know if more of such changes would be introduced and the stability of the API for production.

Thanks

**Comment by fathermerry** [comment]
Sorry for the late reply. It's stable now. We put it out in beta, and it took a while for us to get feedback from people to finally make it a stable API

**Comment by iC00kScripts** [comment]
I am also putting this into production, but, I do hope the api won't trip offline often as it's to be used in a critical system. Thanks
